version: '3.7'
services:

  gatewayserver:
    image: gatewayserv:latest
    ports:
      - "8072:8072"
    environment:
      SPRING_CLOUD_CONFIG_URI:
        http://192.168.0.207:8071
      CONFIGSERVER_PORT: "8071"
    networks:
      backend:
        aliases:
          - "gatewayserv"
networks:
  backend:
    external:
      name: backendnetwork