version: '3.7'
services:

  gatewayserver:
    image: gatewayserv:latest
    ports:
      - "8072:8072"
    environment:
      SPRING_CLOUD_CONFIG_URI: "http://192.168.0.207:8071"
      CONFIGSERVER_PORT: "8071"
      EUREKASERVER_URI: "http://192.168.0.207:8070/eureka/"
      EUREKASERVER_PORT: "8070"
    networks:
      backend:
        aliases:
          - "gatewayserv"
networks:
  backend:
    external:
      name: backendnetwork